[character]
success_symbol = "[ï¬¦](bold green)"
error_symbol = "[ï¦Ÿ](bold red)"
vicmd_symbol = "[î˜«](bold green)"

[aws]
format = 'on [$symbol ($profile )(\($region\) )(\[$duration\])]($style) '
symbol = 'ï‰°'
style = '#EC912D'

[conda]
format = 'via [$symbol env:$environment]($style) '
symbol = 'ðŸ¤–'
style = '#43B02A'
ignore_base = false

[dart]
format = 'via [$symbol($version )]($style) '
symbol = '#45D1FD'

[git_branch]
format = 'on [$symbol git:$branch]($style) '
symbol = 'îœ¥'
style = '#CE9178'

[nodejs]
style = '#9ECE6A'
