[character]
success_symbol = "[ï¬¦](bold green)"
error_symbol = "[ï¦Ÿ](bold red)"
vicmd_symbol = "[î˜«](bold green)"

[cmd_duration]
min_time = 500

[aws]
format = 'on [$symbol ($profile )(\($region\) )(\[$duration\])]($style) '
symbol = 'ï‰°'
style = '#EC912D'

[conda]
format = 'via [$symbol env:$environment]($style) '
ignore_base = false
symbol = 'ğŸ¤–'
style = '#43B02A'

[dart]
format = 'via [$symbol($version )]($style) '
symbol = '#45D1FD'

[git_branch]
format = 'on [$symbol git:$branch]($style) '
symbol = 'îœ¥'
style = '#CE9178'

[git_commit]
format = '[\\($hash\\)]($style) [\\($tag\\)]($style) '
style = 'green'
tag_symbol = 'ğŸ”–'

[git_status]
disabled = false
format = '[$all_status$ahead_behind]($style) '
ahead = 'ï¢ '
behind = 'ï£ '
deleted = 'ï™™ '
diverged = 'ï‘¨'
modified = 'ï«•'
renamed = 'ï±´'
staged = 'ï¤˜'
untracked = 'ï¬¤'
style = '#CE9178'

[golang]
format = 'via [$symbol go:($version)]($style) '
style = '#7FD5EA'

[lua]
style = '#030380'

[nodejs]
style = '#9ECE6A'

[python]
style = '#FFD344'

