shell:
  program: "C:\\Windows\\System32\\wsl.exe ~"

# Window configuration
window:
  padding:
    x: 4
    y: 4

  # Window title
  title: Alacritty

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true

# Font configuration
font:
  normal:
    family: CaskaydiaCove NF
    style: Regular

  italic:
    family: Cascadia Code
    style: Italic

  size: 11.0

colors:
  # Default colors
  primary:
    background: '0x24292e'
    foreground: '0xd1d5da'

  # Normal colors
  normal:
    black:   '0x24292e'
    red:     '0xf14c4c'
    green:   '0x23d18b'
    yellow:  '0xe2e210'
    blue:    '0x3b8eea'
    magenta: '0xbc3fbc'
    cyan:    '0x29b7da'

    white:   '0xd1d5da'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xf14c4c'
    green:   '0x23d18b'
    yellow:  '0xf5f543'
    blue:    '0x3b8eea'

    magenta: '0xd670d6'
    cyan:    '0x29b7da'
    white:   '0xd1d5da'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xf14c4c' }

cursor:
  # Cursor style
  style:
    # Values for `shape`:
    #   - â–‡ Block
    #   - _ Underline
    #   - | Beam
    shape: Block
    blinking: Off

# Live config reload (changes require restart)
live_config_reload: true
